import type { Metadata } from 'next';
import { Poppins, Aclonica } from 'next/font/google';
import '@/styles/global.css';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
	variable: '--poppins',
	display: 'swap',
});

export const aclonica = Aclonica({
	subsets: ['latin'],
	weight: '400',
	variable: '--aclonica',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={`${poppins.className}`}>
			<body className={`bg-background`}>{children}</body>
		</html>
	);
}
