import { Book } from '@/@types/book';

export const testBookList: Book[] = [
  {
    id: '1',
    author: 'Sean Carson',
    title: 'test title 1',
    cover_url: '',
    current_page: 15,
    finished_date: null,
    genres: [],
    language: 'Portuguese',
    started_date: null,
    status: 'To read',
    total_pages: 461,
    book_price: '31.12',
    review: 'test',
    qtd_days: 134,
  },
  {
    id: '2',
    author: 'Elizabeth Cooper',
    title: 'test title 2',
    cover_url: '',
    current_page: 15,
    finished_date: '2024-11-19',
    genres: [],
    language: 'Portuguese',
    started_date: '2024-03-24',
    status: 'Reading',
    total_pages: 461,
    book_price: '31.12',
    review: 'test',
    qtd_days: 134,
  },
  {
    id: '3',
    author: 'Isaiah Townsend',
    title: 'test title 3',
    cover_url: '',
    current_page: 15,
    finished_date: '2024-11-19',
    genres: [],
    language: 'Portuguese',
    started_date: '2024-03-24',
    status: 'Finished',
    total_pages: 461,
    book_price: '31.12',
    review: 'test',
    qtd_days: 134,
  },
];
